# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml

build_vnc_qtonly:
  stage: build
  image: ubuntu:22.04
  tags:
    - Linux
  before_script:
    - sed -i -e 's/# deb-src/deb-src/g' /etc/apt/sources.list
    - apt-get update
    - apt-get install --yes eatmydata
    # - eatmydata apt-get build-dep --yes --no-install-recommends krdc
    # We need this while Ubuntu krdc is qt5 based, remove this and uncomment above
    # once that is no longer true
    - eatmydata apt-get install --yes cmake g++ extra-cmake-modules qt6-base-dev mesa-common-dev libvncserver-dev
    - eatmydata apt-get install --yes --no-install-recommends ninja-build pkg-config
  script:
    - mkdir -p build && cd build
    - cmake -G Ninja ../vnc/qtonly/
    - ninja
