# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kdnssd': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kbookmarks': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kactivities': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kdnssd': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kbookmarks': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kactivities': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
