# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kdnssd': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kbookmarks': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'plasma/plasma-activities': '@latest-kf6'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
