# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kdnssd': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kbookmarks': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kactivities': '@stable'
